[phases]
[phases.setup]
commands = ["mvn install -DskipTests"]

[phases.build]
commands = ["mvn package"]

[phases.start]
commands = ["java -jar target/demo-0.0.1-SNAPSHOT.jar"]

[environment]
JAVA_VERSION = "17"  # Specify the Java version you are using